sudo: false

language: node_js

node_js:
  - 'iojs'
  - '0.10'
  - '0.12'

before_script:
  - mysql -e 'create database IF NOT EXISTS test;' -uroot

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
