sudo: false

language: node_js

node_js:
  - '0.12'

services:
  - elasticsearch

before_script:
  - mysql -e 'create database IF NOT EXISTS test;' -uroot
  - node scripts/import.js
  - cp .env.test .env

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
